//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_ScrapHead
    {
        public int Id { get; set; }
        public string ScrapNo { get; set; }
        public string ScrapUser { get; set; }
        public string ScrapDept { get; set; }
        public Nullable<System.DateTime> ScrapDate { get; set; }
        public string UsingRegion { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> ScrapStatus { get; set; }
        public string ScrapReason { get; set; }
    }
}
