//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_Registration
    {
        public int Id { get; set; }
        public Nullable<int> ApplyLineId { get; set; }
        public string VendorName { get; set; }
        public string AssetNo { get; set; }
        public string AssetCategory { get; set; }
        public string AssetName { get; set; }
        public string AssetSpec { get; set; }
        public string AssetDescribe { get; set; }
        public string UsingRegion { get; set; }
        public Nullable<decimal> ApplyCount { get; set; }
        public Nullable<decimal> RegisterCount { get; set; }
        public Nullable<decimal> StockCount { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Unit { get; set; }
        public Nullable<int> BarCodeCount { get; set; }
        public string SNNo { get; set; }
        public string ApplyNo { get; set; }
        public string ApplyUser { get; set; }
        public string ApplyDept { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> AssetStatus { get; set; }
        public string Remark { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> RegistDate { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public string PrintNo { get; set; }
    }
}
