//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_ApplyHead
    {
        public int Id { get; set; }
        public string ApplyUser { get; set; }
        public string UsingPerson { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<System.DateTime> DemandDate { get; set; }
        public string ApplyReason { get; set; }
        public string Remark { get; set; }
        public string ApplyNo { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<int> ApplyStatus { get; set; }
        public string DisposeReason { get; set; }
        public Nullable<System.DateTime> DisposeDate { get; set; }
        public string DisposeBy { get; set; }
        public string ApplyDept { get; set; }
    }
}
