//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_ClaimLine
    {
        public int Id { get; set; }
        public string AssetNo { get; set; }
        public string AssetCategory { get; set; }
        public string AssetName { get; set; }
        public string AssetSpec { get; set; }
        public string AssetDescribe { get; set; }
        public Nullable<decimal> ClaimCount { get; set; }
        public string Unit { get; set; }
        public Nullable<int> ClaimHeadId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> AssetRegistId { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<bool> AssetStatus { get; set; }
    }
}
