//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_Location
    {
        public int ID { get; set; }
        public string VendorName { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> WarehousID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsBounded { get; set; }
        public Nullable<double> LocationLength { get; set; }
        public Nullable<double> LocationWidth { get; set; }
        public Nullable<double> LocationHeight { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<bool> IsSerialNumberMatch { get; set; }
        public Nullable<bool> IsAutoPrintBarcode { get; set; }
        public Nullable<int> OutPriority { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public Nullable<bool> IsRefBin { get; set; }
    
        public virtual b_Location b_Location1 { get; set; }
        public virtual b_Location b_Location2 { get; set; }
    }
}
