//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_Vendors
    {
        public int Id { get; set; }
        public string VendorName { get; set; }
        public string Shortname { get; set; }
        public string FullName { get; set; }
        public string Contactor { get; set; }
        public string Country { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Address1 { get; set; }
        public Nullable<int> Address1ID { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> Address2ID { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> Address3ID { get; set; }
        public string Address4 { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Zip { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remark { get; set; }
        public Nullable<int> KeyID { get; set; }
        public Nullable<bool> MergeByH200Index { get; set; }
    }
}
