//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIQ_Web_App_Menus
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string TextCH { get; set; }
        public string TextEN { get; set; }
        public string Url { get; set; }
        public string Target { get; set; }
        public string MenuValue { get; set; }
        public Nullable<decimal> SortNumber { get; set; }
        public Nullable<int> IsDisable { get; set; }
        public Nullable<int> Role { get; set; }
        public string PageCode { get; set; }
        public string PageTitle { get; set; }
        public string PageDescription { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsExternal { get; set; }
    }
}
