//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyUIDBEF : DbContext
    {
        public EasyUIDBEF()
            : base("name=EasyUIDBEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Asset_ApplyHead> Asset_ApplyHead { get; set; }
        public DbSet<Asset_ApplyLine> Asset_ApplyLine { get; set; }
        public DbSet<Asset_BarCodeConfig> Asset_BarCodeConfig { get; set; }
        public DbSet<Asset_ClaimHead> Asset_ClaimHead { get; set; }
        public DbSet<Asset_ClaimLine> Asset_ClaimLine { get; set; }
        public DbSet<Asset_CountGrowth> Asset_CountGrowth { get; set; }
        public DbSet<Asset_Region> Asset_Region { get; set; }
        public DbSet<Asset_Registration> Asset_Registration { get; set; }
        public DbSet<Asset_ReturnHead> Asset_ReturnHead { get; set; }
        public DbSet<Asset_ReturnLine> Asset_ReturnLine { get; set; }
        public DbSet<Asset_ScrapHead> Asset_ScrapHead { get; set; }
        public DbSet<Asset_ScrapLine> Asset_ScrapLine { get; set; }
        public DbSet<b_Location> b_Location { get; set; }
        public DbSet<b_Vendors> b_Vendors { get; set; }
        public DbSet<g_u_RoleInfo> g_u_RoleInfo { get; set; }
        public DbSet<g_u_UserInfo> g_u_UserInfo { get; set; }
        public DbSet<g_u_UserLoginHistory> g_u_UserLoginHistory { get; set; }
        public DbSet<Test> Test { get; set; }
        public DbSet<b_Departs> b_Departs { get; set; }
        public DbSet<CIQ_Web_App_Menus> CIQ_Web_App_Menus { get; set; }
        public DbSet<S_City> S_City { get; set; }
        public DbSet<S_District> S_District { get; set; }
        public DbSet<S_Province> S_Province { get; set; }
    }
}
