//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Menu
    {
        public int ID { get; set; }
        public Nullable<int> MenuCode { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Description { get; set; }
        public string MenuUrl { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> IsInUse { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string AddUser { get; set; }
        public Nullable<int> AddUserID { get; set; }
    }
}
