//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int uId { get; set; }
        public string uName { get; set; }
        public string uLoginName { get; set; }
        public string uPwd { get; set; }
        public System.DateTime uAddtime { get; set; }
        public bool uIsDel { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<byte> AccountState { get; set; }
        public Nullable<int> PowerLevelID { get; set; }
    }
}
